version: '3.3'

services:
  linear-webhook:
    image: ghcr.io/allen0125/vibecodingci:latest
    container_name: linear-webhook-handler
    ports:
      - "9900:8000"
    env_file:
      - .env
    volumes:
      # 持久化数据
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
